# Generated by Django 4.2.2 on 2023-06-24 07:44

import django.core.validators
from django.db import migrations, models
import fruitipedia.fruitipedia_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fruitipedia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), fruitipedia.fruitipedia_app.validators.validate_contains_letters_only])),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
